#%RAML 1.0 Library
uses:
  stores: stores.raml

types:
  SuccessAlert:
    type: !include successType.raml
    properties:
      data: Alert

  SuccessAlerts:
    type: !include successType.raml
    properties:
      data: Alert[]

  Alert:
    type: object
    properties:
      id: string
      tags: string[]
      info: string
      description?: string
      img?:
        type: file
        fileTypes: ['image/jpeg', 'image/png']
