#  Experience APIs => ./experience/
mobile_api:
  build: ./experience/mobile-api/
  container_name: mobile-api

web_api:
  build: ./experience/web-api/
  container_name: web-api

# Process APIs => ./process/
location:
  build: ./process/location/
  container_name: location

engagement:
  build: ./process/engagement
  container_name: engagement

accounts:
  build: ./process/accounts
  container_name: accounts

marketing:
  build: ./process/marketing
  container_name: marketing

warehouse:
  build: ./process/warehouse
  container_name: warehouse

stores_management:
  build: ./process/stores-management/
  container_name: stores-management

# System APIs => ./system/
stores:
  build: ./system/stores
  container_name: stores

products:
  build: ./system/products
  container_name: products

campaigns:
  build: ./system/campaigns
  container_name: campaigns

users:
  build: ./system/users
  container_name: users

find_service:
  build: ./system/find
  container_name: find_service


# Storages & other infra
stores_db:
  image: mongo:3.2.7
  volumes_from:
    - stores_db__data_volume
  ports:
    - 11015:27017

stores_db__data_volume:
  image: mongo:3.2.7
  volumes:
    - /data/db
  command: /bin/true

products_db:
  image: mongo:3.2.7
  volumes_from:
    - products_db__data_volume
  ports:
    - 11016:27017

products_db__data_volume:
  image: mongo:3.2.7
  volumes:
    - /data/db
  command: /bin/true

users_db:
  image: mongo:3.2.7
  volumes_from:
    - users_db__data_volume
  ports:
    - 11017:27017

users_db__data_volume:
  image: mongo:3.2.7
  volumes:
    - /data/db
  command: /bin/true

ads_db:
  image: mongo:3.2.7
  volumes_from:
    - ads_db__data_volume
  ports:
    - 11018:27017

ads_db__data_volume:
  image: mongo:3.2.7
  volumes:
    - /data/db
  command: /bin/true

find:
  image: sebastianbogado/find
  volumes_from:
    - find__data_volume
  ports:
    - 11019:8003

find__data_volume:
  image: sebastianbogado/find
  volumes:
    - /go/src/app/data
  command: /bin/true
