#  Experience APIs
mobile_api:
  build: ./experience/mobile-api/
  container_name: mobile-api

# Process APIs
location:
  build: ./process/location/
  container_name: location

# System APIs
stores:
  build: ./system/stores
  container_name: stores

# Storages & other infra
stores_db:
  image: mongo:3.2.7
  volumes_from:
    - stores_db__data_volume
  ports:
    - 11000:27017

stores_db__data_volume:
  image: mongo:3.2.7
  volumes:
    - /data/db
  command: /bin/true

find:
  image: sebastianbogado/find
  volumes_from:
    - find__data_volume
  ports:
    - 11001:8003

find__data_volume:
  image: sebastianbogado/find
  volumes:
    - /go/src/app/data
  command: /bin/true
