#  Experience APIs
mobileApi:
  build: ./experience/mobile-api/
  container_name: mobile-api

# Process APIs
location:
  build: ./process/location/
  container_name: location

# System APIs
stores:
  build: ./system/stores
  container_name: stores

# Storages & other infra
storesDb:
  image: mongo:3.2.7
  ports:
    - 10003:27017
