#%RAML 1.0 Library
usage: Marketing related types

types:
  SimpleAd: !include simpleObject.raml

  SuccessCampaign:
    type: !include successType.raml
    properties:
      data: Campaign

  SuccessCampaigns:
    type: !include successType.raml
    properties:
      data: Campaign[]

  SuccessAd:
    type: !include successType.raml
    properties:
      data: Ad

  SuccessAds:
    type: !include successType.raml
    properties:
      data: Ad[]

  Campaign:
    description: |
      A Campaign is a group of interchangeable Ads that are related to each other.
      When a given Campaign is applied, any of the Ads that compose it can be used to represent it.
    type: object
    properties:
      id: string
      name: string
      tags:
        description: Set of Tags used to identify when to apply this Campaign
        type: string[]
      ads:
        description: Set of Ads that are part of this Campaign
        type: SimpleAd[]
      expiration?:
        description: |
          Date in which this Campaign ends and stops being shown even if the are tag matches.
          For example, a christmas campaign should automatically end after christmas.
        type: date-only
        example: 2016-11-23

  Ad:
    description: Simple marketing message transmitted within an image
    type: object
    properties:
      id: string
      name: string
      engagementLink:
        type: string
        description: engagement link to allow the user to enter the store in a unique way
      img:
        type: file
        fileTypes: ['image/jpeg', 'image/png']
      tags:
        description: Set of Tags used to identify when to apply this Ad
        type: string[]
      expiration?:
        type: datetime-only
        example: 2016-12-24T22:00:00
      _links?:
        type: object
        properties:
          access: string
