#%RAML 1.0 Library
types:
  Product:
    description: A product that can be available in any Store
    type: object
    properties:
      id: string
      name: string
      tags:
        description: Set of tags used to match this product when filtering by client preferences
        type: string[]
      description?: string
      img:
        type: file
        fileTypes: ['image/jpeg', 'image/png']

  CartProduct:
    type: Product
    properties:
      quantity: integer
      price: number

  Cart:
    description: Keeps track of the products while the user is buying
    type: object
    properties:
      id: string
      total: number
      products: CartProduct[]
      discount?: integer

  SuccessCart:
    type: !include successType.raml
    properties:
      data: Cart

  SuccessProduct:
    type: !include successType.raml
    properties:
      data: Product

  SuccessProducts:
    type: !include successType.raml
    properties:
      data: Product[]
