#%RAML 1.0 Library
uses:
  locations: locations.raml

usage: Store related types
types:

  Store:
    type: object
    properties:
      id: string
      name: string
      ownerId: string
      stock: ProductStock[]
      locations:
        description: Set of Locations placed near or inside this Store
        type: string[]
      campaignTags?:
        description: Set of tags used to identify if a Campaign applies to this Store
        type: string[]
      adTags?:
        description: Set of tags used to identify if an Ad applies to this Store
        type: string[]

  ProductStock:
    description: References a product as part of the Stock of some Store or WareHouse
    type: object
    properties:
      productId: string
      price: number
      stock: number

  SuccessStore:
    type: !include successType.raml
    properties:
      data: Store

  SuccessStores:
    type: !include successType.raml
    properties:
      data: Store
  SuccessStock:
    type: !include successType.raml
    properties:
      data: ProductStock[]
