#%RAML 1.0 Library
uses:
  stores: stores.raml

types:
  SuccessProduct:
    type: !include successType.raml
    properties:
      data: Product

  SuccessStock:
    type: !include successType.raml
    properties:
      data: Product[]

  Product:
    type: object
    properties:
      id: string
      name: string
      ownerId: string
      description?: string
      price?: number
      store?: stores.Store
      tags?: string[]
      img?:
        type: file
        fileTypes: ['image/jpeg', 'image/png']
