#%RAML 1.0 ResourceType

usage: |
  This resourceType should be used for any collection of items

description: The collection of <<resourcePathName>>
get:
  description: Get all <<resourcePathName>>, optionally filtered
  responses:
    400:
      body:
        application/json:
          type: !include ../errorType.raml
    404:
      body:
        application/json:
          type: !include ../errorType.raml

    500:
      body:
        application/json:
          type: !include ../errorType.raml
post:
  description: Create a new <<resourcePathName | !singularize>>
  responses:
    400:
      body:
        application/json:
          type: !include ../errorType.raml
    404:
      body:
        application/json:
          type: !include ../errorType.raml
    405:
      body:
        application/json:
          type: !include ../errorType.raml
    500:
      body:
        application/json:
          type: !include ../errorType.raml
