#%RAML 1.0
title: GitHub API
version: v1
baseUri: https://www.nearb.com/v1/process/location
mediaType:  application/json

uses:
  locations: types/locations.raml
  stores: types/stores.raml


/locate:
  get:
    queryParameters:
      username:
        type: string
        required: false
        description: the username of the user that requests to be located
      beacons:
        type: string
        required: true
        description: |
          Set of fingerprints expressed as mac=level tuples. In the example we have two fingerprints,
          the first one is 24:a4:3c:9e:d2:84=16 and the second 32:a4:3c:9e:d2:84=10
        example: ?24%3Aa4%3A3c%3A9e%3Ad2%3A84%3D16%2C32%3Aa4%3A3c%3A9e%3Ad2%3A84%3D10
    responses:
      200:
        body:
          application/json:
            type: locations.SuccessLocations

/locations:
  put:
    body:
      application/json:
        type: locations.TrackingInformation
    responses:
      200:
        body:
          application/json:
            type: locations.SuccessLocation

  get:
    responses:
      200:
        body:
          application/json:
            type: locations.SuccessLocations

  /{locationId}:
    delete:
      description: |
        Removes the location identified by <<locationId>> where
        locationId has the format storeName:locationName

      responses:
        200:
          description: Returns the remaining locations
          body:
            application/json:
              type: !include types/successType.raml

/discover:
  description: Endpoint used to discover stores based on location.
  get:
    queryParameters:
      geo?:
        type: string
        description: |
          Discover nearby stores based on geo location
          csv coordinates with the format: lat,long,searchRadio with radio in meters
        example: ?geo=-34.6375814,-58.4344577,15z,1000
      username?:
        type: string
        description: to be used along beacons
      beacons?:
        type: string
        description: |
          Discover nearby stores beacons fingerprints
          Set of fingerprints expressed as mac=level tuples. In the example we have two fingerprints,
          the first one is 24:a4:3c:9e:d2:84=16 and the second 32:a4:3c:9e:d2:84=10
        example: ?beacon=24%3Aa4%3A3c%3A9e%3Ad2%3A84%3D16%2C32%3Aa4%3A3c%3A9e%3Ad2%3A84%3D10
      locations?:
        type: string
        description: |
          Discover nearby stores locations
          a csv collection of locationId as provided by this service
        example: ?locations=baoou3223g4,baiubkh231g4
